---

- name: Install essential packages
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Install fish shell
      apt:
        name: fish
        state: present

    - name: Install nala frontend for apt
      apt:
        name: nala
        state: present 
